---
- name: Apply Kubernetes Configuration after making changes
  hosts: node
  become: yes
  tasks:

    - name: Apply Backend Deployment
      command: kubectl apply -f /home/user/config-kbs/Deployment.yml
      environment:
        KUBECONFIG: /home/user/.kube/config

    - name: Apply Backend Service
      command: kubectl apply -f /home/user/config-kbs/Service.yml
      environment:
        KUBECONFIG: /home/user/.kube/config

    - name: Apply Frontend Deployment
      command: kubectl apply -f /home/user/config-kbs/Frontend-Deployment.yml
      environment:
        KUBECONFIG: /home/user/.kube/config

    - name: Apply Frontend Service
      command: kubectl apply -f /home/user/config-kbs/Frontend-Service.yml
      environment:
        KUBECONFIG: /home/user/.kube/config

