kind: Service
apiVersion: v1
metadata:
  name: devops-pos
  labels:
    app: devops-pos
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: devops-pos
  type: LoadBalancer

